console.log("hello world!");
console.log("kaushiki parmar");
let a=10;
let b=20;
console.log("sum is:", a+b);
let pencil=20;
let erasor=30;
let output=`the total price is: ${pencil+erasor} rupees`;
console.log(output);
let a=35;
let c=56;
console.log(c-a);